/* Flight-list station weather screen. Supplementary planning information only. */
const bulk$=id=>document.getElementById(id);
let bulkOutput=[],bulkInputHeaders=[];
const bulkCache={airport:new Map(),taf:new Map(),model:new Map()};
const bulkNotice=(message,type='')=>{const node=bulk$('bulkNotice');node.textContent=message;node.className=`bulk-notice ${type}`;};
const safeText=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const normalizedHeader=value=>String(value||'').trim().toLowerCase().replace(/[^a-z0-9]/g,'');
const requiredHeaders={flightno:'Flight No',departure:'Departure',arrival:'Arrival',depttime:'Dept Time',arrivtime:'Arriv Time'};

function setBulkMonth(){bulk$('scheduleMonth').value=new Date().toISOString().slice(0,7);}
function readFlightFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('The file could not be read.'));reader.onload=()=>{try{if(/\.(xlsx|xls)$/i.test(file.name)){if(!window.XLSX)throw new Error('Excel support did not load. Refresh and try again.');const workbook=XLSX.read(reader.result,{type:'array'}),sheet=workbook.Sheets[workbook.SheetNames[0]];resolve(XLSX.utils.sheet_to_json(sheet,{defval:'',raw:false}));}else{const text=String(reader.result||''),lines=text.split(/\r?\n/).filter(line=>line.trim());if(!lines.length)throw new Error('The file is empty.');const separator=(lines[0].match(/,/g)||[]).length>=(lines[0].match(/\t/g)||[]).length?',':'\t';const parse=line=>line.split(separator).map(value=>value.trim().replace(/^"|"$/g,''));const headers=parse(lines[0]);resolve(lines.slice(1).map(line=>Object.fromEntries(parse(line).map((value,index)=>[headers[index]||`Column ${index+1}`,value]))));}}catch(error){reject(error);}};if(/\.(xlsx|xls)$/i.test(file.name))reader.readAsArrayBuffer(file);else reader.readAsText(file);});}
function canonicalRows(rows){if(!rows.length)throw new Error('The file has no flight rows.');const sample=Object.keys(rows[0]),headerMap=Object.fromEntries(sample.map(key=>[normalizedHeader(key),key]));bulkInputHeaders=sample;const missing=Object.entries(requiredHeaders).filter(([key])=>!headerMap[key]).map(([,label])=>label);if(missing.length)throw new Error(`Missing required column${missing.length>1?'s':''}: ${missing.join(', ')}.`);return rows.map((row,index)=>({...row,_row:index+2,flightNo:String(row[headerMap.flightno]||'').trim(),departure:String(row[headerMap.departure]||'').trim().toUpperCase(),arrival:String(row[headerMap.arrival]||'').trim(),deptTime:String(row[headerMap.depttime]||'').trim(),arrivTime:String(row[headerMap.arrivtime]||'').trim()}));}
function parseScheduleTime(value,month){const match=String(value).match(/^(\d{2})(\d{2})\/(\d{1,2})$/);if(!match)throw new Error(`Invalid time “${value}”. Use HHMM/DD, for example 1836/16.`);const hour=Number(match[1]),minute=Number(match[2]),day=Number(match[3]);if(hour>23||minute>59||day<1||day>31)throw new Error(`Invalid time “${value}”.`);const [year,monthNumber]=month.split('-').map(Number),date=new Date(Date.UTC(year,monthNumber-1,day,hour,minute));if(date.getUTCMonth()!==monthNumber-1)throw new Error(`Day ${day} is not in the selected schedule month.`);return date;}
async function airportForIata(iata){if(!/^[A-Z]{3}$/.test(iata))throw new Error(`“${iata}” is not a valid three-letter IATA code.`);if(!bulkCache.airport.has(iata))bulkCache.airport.set(iata,fetch(`/api/iata-airport?code=${encodeURIComponent(iata)}`).then(async response=>{const data=await response.json();if(!response.ok||!Array.isArray(data)||!data.length)throw new Error(`No airport mapping was found for ${iata}.`);return data[0];}));return bulkCache.airport.get(iata);}
async function tafForAirport(icao){if(!bulkCache.taf.has(icao))bulkCache.taf.set(icao,fetch(`/api/taf?icao=${encodeURIComponent(icao)}`).then(async response=>{if(!response.ok)return [];const data=await response.json(),reports=Array.isArray(data)?data:data?.data||[];return reports.map(report=>({raw:String(report.rawTAF||report.raw_text||report.rawText||''),forecasts:(report.fcsts||[]).map(forecast=>({timeFrom:new Date((forecast.timeFrom||0)*1000),timeTo:new Date((forecast.timeTo||0)*1000),weather:forecast.wxString,gust:Number(forecast.wgst),visibility:forecast.visib}))}));}).catch(()=>[]));return bulkCache.taf.get(icao);}
async function modelForAirport(airport,start,end){const key=`${airport.icao}|${start.toISOString().slice(0,10)}|${end.toISOString().slice(0,10)}`;if(!bulkCache.model.has(key)){const params=new URLSearchParams({source:'ensemble',latitude:airport.lat,longitude:airport.lon,start_date:start.toISOString().slice(0,10),end_date:end.toISOString().slice(0,10),models:'ecmwf_ifs025_ensemble',timezone:'GMT'});bulkCache.model.set(key,fetch(`/api/open-meteo?${params}`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||'Open-Meteo ensemble guidance was unavailable.');return data;}));}return bulkCache.model.get(key);}
function severity(level){return {Low:0,Moderate:1,High:2}[level]??0;}
function appendRisk(items,level,text){items.push({level,text});}
function ensembleValue(hourly,key,index){const values=Object.entries(hourly).filter(([name])=>name===key||name.startsWith(`${key}_member`)).map(([,series])=>Number(series?.[index])).filter(Number.isFinite);return values.length?values.reduce((sum,value)=>sum+value,0)/values.length:Number.NaN;}
function modelRisks(model,start,end,station){const hourly=model?.hourly||{},times=hourly.time||[],items=[];for(let index=0;index<times.length;index++){const time=new Date(`${times[index]}Z`);if(time<start||time>end)continue;const code=Math.round(ensembleValue(hourly,'weather_code',index)),precip=ensembleValue(hourly,'precipitation',index),gust=ensembleValue(hourly,'wind_gusts_10m',index),vis=ensembleValue(hourly,'visibility',index),cape=ensembleValue(hourly,'cape',index),when=new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(time).replace(',','');if([95,96,99].includes(code)||((cape>=750)&&precip>=.5))appendRisk(items,'High',`${station}: thunderstorm / convection signal near ${when} UTC (Model ensemble forecast).`);else if(precip>=2)appendRisk(items,'High',`${station}: heavy precipitation near ${when} UTC (Model ensemble forecast).`);else if(precip>=.5)appendRisk(items,'Moderate',`${station}: precipitation signal near ${when} UTC (Model ensemble forecast).`);if(gust>=40)appendRisk(items,'High',`${station}: gusts ${Math.round(gust)} kt near ${when} UTC (Model ensemble forecast).`);else if(gust>=30)appendRisk(items,'Moderate',`${station}: gusts ${Math.round(gust)} kt near ${when} UTC (Model ensemble forecast).`);if(vis>0&&vis<1000)appendRisk(items,'High',`${station}: visibility around ${(vis/1000).toFixed(1)} km near ${when} UTC (Model ensemble forecast).`);else if(vis>0&&vis<3000)appendRisk(items,'Moderate',`${station}: visibility around ${(vis/1000).toFixed(1)} km near ${when} UTC (Model ensemble forecast).`);}return items;}
function tafVisibilityMetres(value){const text=String(value||'').trim();if(!text||text.includes('+'))return Number.NaN;const n=Number(text);return Number.isFinite(n)?(n>=9999?n:n*1609.344):Number.NaN;}
function tafRisks(reports,start,end,station){const items=[];for(const report of reports){for(const forecast of report.forecasts||[]){const from=forecast.timeFrom||start,to=forecast.timeTo||end;if(from>end||to<start)continue;const text=`${forecast.weather||''} ${report.raw||''}`.toUpperCase(),when=new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(from).replace(',',''),vis=tafVisibilityMetres(forecast.visibility);if(/TS|FZRA|GR/.test(text))appendRisk(items,'High',`${station}: ${/TS/.test(text)?'thunderstorm':'freezing precipitation / hail'} forecast from ${when} UTC (AWC TAF).`);if(vis>0&&vis<3000)appendRisk(items,'High',`${station}: visibility ${(vis/1000).toFixed(1)} km forecast from ${when} UTC (AWC TAF).`);else if(vis>0&&vis<5000)appendRisk(items,'Moderate',`${station}: reduced visibility ${(vis/1000).toFixed(1)} km forecast from ${when} UTC (AWC TAF).`);if(Number(forecast.gust)>=40)appendRisk(items,'High',`${station}: gusts ${Math.round(forecast.gust)} kt forecast from ${when} UTC (AWC TAF).`);else if(Number(forecast.gust)>=30)appendRisk(items,'Moderate',`${station}: gusts ${Math.round(forecast.gust)} kt forecast from ${when} UTC (AWC TAF).`);}}return items;}
function makeAssessment(items){if(!items.length)return {level:'Low',text:'No significant weather risk detected in available TAF or model ensemble forecast.'};const top=Math.max(...items.map(item=>severity(item.level))),level=['Low','Moderate','High'][top],unique=[...new Set(items.filter(item=>severity(item.level)===top).map(item=>item.text))].slice(0,4);return {level,text:unique.join(' ')};}
async function analyseFlight(row,month){const departureTime=parseScheduleTime(row.deptTime,month),arrivalTime=parseScheduleTime(row.arrivTime,month);if(arrivalTime<departureTime)arrivalTime.setUTCDate(arrivalTime.getUTCDate()+1);if(arrivalTime-departureTime>36*3600e3)throw new Error('Arrival must be within 36 hours of departure.');const arrival=await airportForIata(row.arrival),start=new Date(departureTime.getTime()-60*60e3),end=new Date(arrivalTime.getTime()+60*60e3),[arrivalTaf,arrivalModel]=await Promise.all([tafForAirport(arrival.icao),modelForAirport(arrival,start,end).catch(error=>{console.warn('Ensemble guidance unavailable',error);return null;})]),station=`${row.arrival} / ${arrival.icao}`,risks=[...tafRisks(arrivalTaf,start,end,station),...modelRisks(arrivalModel,start,end,station)],assessment=makeAssessment(risks);if(!arrivalModel)assessment.text=`${assessment.text} Model ensemble forecast was temporarily unavailable.`;return {...row,'Risk Level':assessment.level,'Weather Risk Assessment':assessment.text};}
function renderBulk(rows){const headers=[...bulkInputHeaders,'Weather Risk'];bulk$('bulkHead').innerHTML=`<tr>${headers.map(header=>`<th>${safeText(header)}</th>`).join('')}</tr>`;bulk$('bulkBody').innerHTML=rows.map(row=>`<tr>${headers.map(header=>`<td class="${header==='Weather Risk'?`risk-${String(row['Risk Level']||'Low').toLowerCase()}`:''}">${safeText(header==='Weather Risk'?row['Weather Risk Assessment']:row[header]??'')}</td>`).join('')}</tr>`).join('');bulk$('bulkResults').classList.remove('hidden');}
function exportBulk(type){const rows=bulkOutput.map(row=>Object.fromEntries([...bulkInputHeaders,'Weather Risk'].map(header=>[header,header==='Weather Risk'?row['Weather Risk Assessment']:row[header]??''])));if(type==='xlsx'){const sheet=XLSX.utils.json_to_sheet(rows),book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,'Weather risk review');XLSX.writeFile(book,'flight-weather-risk-review.xlsx');return;}const headers=Object.keys(rows[0]);const csv=[headers.join(','),...rows.map(row=>headers.map(header=>`"${String(row[header]??'').replaceAll('"','""')}"`).join(','))].join('\n');const link=Object.assign(document.createElement('a'),{href:URL.createObjectURL(new Blob([csv],{type:'text/csv'})),download:'flight-weather-risk-review.csv'});link.click();URL.revokeObjectURL(link.href);}
bulk$('analyseFlightList').addEventListener('click',async()=>{const file=bulk$('flightFile').files[0],month=bulk$('scheduleMonth').value;if(!file)return bulkNotice('Choose a flight-list file first.','error');if(!month)return bulkNotice('Choose the schedule month and year in UTC.','error');try{bulk$('analyseFlightList').disabled=true;bulk$('bulkResults').classList.add('hidden');bulkCache.airport.clear();bulkCache.taf.clear();bulkCache.model.clear();const rows=canonicalRows(await readFlightFile(file));if(rows.length>50)throw new Error('For dependable public-data access, process up to 50 flights per file.');bulkOutput=[];for(let index=0;index<rows.length;index++){bulkNotice(`Analysing flight ${index+1} of ${rows.length}…`);try{bulkOutput.push(await analyseFlight(rows[index],month));}catch(error){bulkOutput.push({...rows[index],'Departure ICAO':'—','Arrival ICAO':'—','Risk Level':'High','Weather Risk Assessment':`Could not complete review: ${error.message}`});}}renderBulk(bulkOutput);bulkNotice(`Completed ${bulkOutput.length} flight reviews. Risk colour reflects the highest detected signal.`);}catch(error){bulkNotice(error.message||'Unable to process the file.','error');}finally{bulk$('analyseFlightList').disabled=false;}});
bulk$('downloadBulkCsv').addEventListener('click',()=>bulkOutput.length&&exportBulk('csv'));bulk$('downloadBulkXlsx').addEventListener('click',()=>bulkOutput.length&&exportBulk('xlsx'));setBulkMonth();
