const tool$=id=>document.getElementById(id),toolFmt=d=>new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(d).replace(',','');let toolRunways={};
const toolNum=v=>v===null||v===undefined||v===''?NaN:Number(v);const toolDate=v=>{const n=Number(v);return new Date(Number.isFinite(n)&&n>1e8?(n<1e12?n*1000:n):v);};
function setToolTime(){const d=new Date();d.setUTCMinutes(0,0,0);d.setUTCHours(d.getUTCHours()+1);tool$('toolTime').value=d.toISOString().slice(0,16);}
async function loadRunways(){toolRunways=await fetch('assets/runways.json').then(r=>r.json());}
function populateRunways(){const icao=tool$('toolIcao').value.trim().toUpperCase(),items=toolRunways[icao]||[];tool$('toolRunway').innerHTML=items.length?items.map((r,i)=>`<option value="${i}">${r.id} · ${Math.round(r.heading)}°T${r.lengthFt?` · ${r.lengthFt.toLocaleString()} ft`:''}</option>`).join(''):'<option>No runway data</option>';return items;}
function components(wind,runway){const angle=(wind.direction-runway.heading)*Math.PI/180,head=wind.speed*Math.cos(angle),cross=wind.speed*Math.sin(angle);return {head:`${head>=0?'Head':'Tail'} ${Math.abs(head).toFixed(1)} kt`,cross:`${cross>=0?'Right':'Left'} ${Math.abs(cross).toFixed(1)} kt`};}
function closestHourly(data,time){const h=data.hourly||{},times=h.time||[];let best=0,delta=Infinity;times.forEach((v,i)=>{const d=Math.abs(new Date(`${v}Z`)-time);if(d<delta){best=i;delta=d;}});return {direction:toolNum(h.wind_direction_10m?.[best]),speed:toolNum(h.wind_speed_10m?.[best]),gust:toolNum(h.wind_gusts_10m?.[best])};}
async function analyse(){const icao=tool$('toolIcao').value.trim().toUpperCase(),time=new Date(`${tool$('toolTime').value}Z`),runways=toolRunways[icao]||[],runway=runways[Number(tool$('toolRunway').value)];if(!/^[A-Z]{4}$/.test(icao)||!runway||Number.isNaN(time))return tool$('toolNotice').textContent='Enter a four-letter ICAO code, a UTC time and an available runway.';tool$('toolNotice').textContent='Loading independent model guidance and AWC bulletins…';try{const metarP=fetch(`/api/metar?icao=${icao}`).then(r=>r.json()),tafP=fetch(`/api/taf?icao=${icao}`).then(r=>r.ok?r.json():[]),modelP=fetch(`/api/open-meteo?source=forecast&latitude=${encodeURIComponent((await metarP).find(x=>x.lat)?.lat||0)}&longitude=${encodeURIComponent((await metarP).find(x=>x.lon)?.lon||0)}&past_days=1&forecast_days=3&models=gfs_global&wind_speed_unit=kn&timezone=GMT`).then(r=>r.json());const [metars,tafs,model]=await Promise.all([metarP,tafP,modelP]);const wind=closestHourly(model,time),taf=(tafs[0]?.fcsts||[]).find(f=>toolDate(f.timeFrom)<=time&&toolDate(f.timeTo)>=time),tafWind=taf?{direction:toolNum(taf.wdir),speed:toolNum(taf.wspd),gust:toolNum(taf.wgst)}:null;const row=(name,w)=>Number.isFinite(w?.direction)&&Number.isFinite(w?.speed)?(()=>{const c=components(w,runway);return `<tr><td>${name}</td><td>${Math.round(w.direction).toString().padStart(3,'0')}° / ${w.speed.toFixed(1)} kt${Number.isFinite(w.gust)?` G${w.gust.toFixed(0)}`:''}</td><td>${c.head}</td><td>${c.cross}</td></tr>`;})():`<tr><td>${name}</td><td colspan="3">No fixed wind forecast available for this time.</td></tr>`;tool$('toolWind').innerHTML=`<p class="calculator-time">${toolFmt(time)} · Runway ${runway.id} (${Math.round(runway.heading)}° true)</p><div class="table-wrap"><table><thead><tr><th>Source</th><th>Wind from / speed</th><th>Headwind / tailwind</th><th>Crosswind</th></tr></thead><tbody>${row('Open-Meteo model guidance',wind)}${row('AWC TAF',tafWind)}</tbody></table></div>`;tool$('toolTaf').textContent=tafs.map(t=>t.rawTAF||t.raw_text||t.rawText||'').filter(Boolean).join('\n\n')||'No current TAF bulletin returned by AWC.';tool$('toolMetar').innerHTML=(metars||[]).filter(m=>toolDate(m.obsTime||m.reportTime)>Date.now()-864e5).map(m=>`<tr><td>${toolFmt(toolDate(m.obsTime||m.reportTime))}</td><td class="raw-metar">${String(m.rawOb||m.raw_text||'')}</td></tr>`).join('')||'<tr><td colspan="2">No METAR in the last 24 hours.</td></tr>';tool$('toolNotice').textContent='Ready.';}catch(e){tool$('toolNotice').textContent=e.message||'Unable to load guidance.';}}
tool$('toolIcao').addEventListener('input',e=>{e.target.value=e.target.value.toUpperCase();populateRunways();});tool$('toolAnalyse').onclick=analyse;loadRunways().then(populateRunways);setToolTime();
