const $=id=>document.getElementById(id),state={systems:[],airports:[],selectedId:null};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const num=v=>Number.isFinite(Number(v))?Number(v):null;
async function api(url){const r=await fetch(url),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||r.statusText);return d}
function utc(v){const d=new Date(v);return Number.isNaN(d)?v||'Not supplied':new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(d).replace(',','')+' UTC'}
function pos(p){return `${Math.abs(p.lat).toFixed(1)}°${p.lat>=0?'N':'S'} ${Math.abs(p.lon).toFixed(1)}°${p.lon>=0?'E':'W'}`}
function basin(s){const {lat,lon}=s.position;if(s.source==='IMD')return lon>=80?'Bay of Bengal · North Indian Ocean':'Arabian Sea · North Indian Ocean';if(s.code?.endsWith('W')||lon>=100)return'Western North Pacific Ocean';if(s.code?.endsWith('E')||lon<-100)return'Eastern North Pacific Ocean';if(lon>=-100&&lon<20&&lat>=0)return'North Atlantic Ocean';return'North Indian Ocean'}
function nm(a,b){const r=Math.PI/180,p1=a.lat*r,p2=b.lat*r,dp=(b.lat-a.lat)*r,dl=(b.lon-a.lon)*r,h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 3440*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
function cls(v){return({TD:'Tropical depression',TS:'Tropical storm',HU:'Hurricane',TY:'Typhoon'}[String(v||'').toUpperCase()]||v||'Tropical cyclone')}
function nhc(data){return(data.activeStorms||[]).map(s=>{const advisory=s.forecastAdvisory?.url||'',discussion=advisory.replace(/TCM([A-Z]{2}\d)\.shtml$/i,'TCD$1.shtml');return{id:`nhc-${s.id}`,source:'NHC / CPHC',name:s.name||s.id,classification:cls(s.classification),intensity:num(s.intensity),pressure:num(s.pressure),movement:Number.isFinite(num(s.movementDir))?`${Math.round(num(s.movementDir))}° / ${num(s.movementSpeed)??'—'} kt`:'—',issued:s.lastUpdate||'',position:{lat:num(s.latitudeNumeric),lon:num(s.longitudeNumeric)},forecast:[],track:s.forecastTrack?.kmzFile,graphic:s.forecastGraphics?.url,advisory,discussionUrl:discussion,links:[['Public advisory',s.publicAdvisory?.url],['Forecast advisory',advisory],['Official discussion',discussion],['Official graphics',s.forecastGraphics?.url]].filter(([,u])=>u)}}).filter(s=>Number.isFinite(s.position.lat)&&Number.isFinite(s.position.lon))}
function jtwc(data){return(data.systems||[]).map(s=>({id:`jtwc-${s.id}`,source:'JTWC · Western Pacific',name:s.name||s.id,classification:s.classification||'Tropical cyclone',intensity:num(s.intensity),pressure:num(s.pressure),movement:s.movement||'Not supplied',issued:s.issued||'',position:{lat:num(s.position?.lat),lon:num(s.position?.lon)},forecast:(s.forecast||[]).map(p=>({lat:num(p.lat),lon:num(p.lon),time:p.time||'',intensity:num(p.intensity)})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon)),graphic:s.graphic_url,discussion:s.discussion||'',textTitle:'Official JTWC warning & forecast discussion',links:[['JTWC warning text',s.warning_url],['JTWC warning graphic',s.graphic_url],['JTWC official warnings','https://www.metoc.navy.mil/jtwc/jtwc.html']].filter(([,u])=>u)})).filter(s=>Number.isFinite(s.position.lat)&&Number.isFinite(s.position.lon))}
function nrl(data,codes){return(data.features||[]).map(x=>x.properties||{}).map(p=>{const id=String(p.storm_id||'').toLowerCase(),m=id.match(/^(wp|ep)(\d{2})/),code=m?`${m[2]}${m[1].toUpperCase()==='EP'?'E':'W'}`:'';if(String(p.storm_name||'').toUpperCase()!=='INVEST'||!codes.has(code))return null;return{id:`nrl-${p.storm_id}`,source:'JTWC basin · U.S. Navy NRL',name:`INVEST ${code}`,classification:cls(p.storm_type),intensity:num(p.vmax),pressure:num(p.pressure),movement:'See official JTWC formation alert',issued:`${p.start_date||''} ${p.start_time||''}`.trim(),position:{lat:num(p.center_latitude),lon:num(p.center_longitude)},forecast:[],code,links:[['JTWC official warnings','https://www.metoc.navy.mil/jtwc/jtwc.html']]}}).filter(s=>s&&Number.isFinite(s.position.lat)&&Number.isFinite(s.position.lon))}
function points(g,issuedAt){const base=new Date(issuedAt).getTime();return(g.features||[]).filter(f=>f.geometry?.type==='Point').map(f=>{const t=f.properties?.description||'',lead=t.match(/(\d+)\s*hr\s+Forecast/i),wind=t.match(/Maximum Wind:\s*(\d+)\s*knots/i);if(!lead)return null;const[lon,lat]=f.geometry.coordinates;return{lat,lon,time:Number.isFinite(base)?new Date(base+Number(lead[1])*36e5).toISOString():'',intensity:num(wind?.[1])}}).filter(Boolean).sort((a,b)=>a.time.localeCompare(b.time))}
function officialDiscussion(html){const d=new DOMParser().parseFromString(String(html||''),'text/html');const text=(d.querySelector('pre')?.textContent||d.body.textContent||'').replace(/\r/g,'').replace(/\n{3,}/g,'\n\n').trim();return /(?:TROPICAL|SUBTROPICAL|POST-TROPICAL).{0,100}DISCUSSION/i.test(text)?text:''}
async function enrich(s){const jobs=[];if(s.track)jobs.push(api(`/api/storms/nhc-geometry?url=${encodeURIComponent(s.track)}`).then(g=>s.forecast=points(g,s.issued)));if(s.graphic)jobs.push(api(`/api/storms/nhc-track-image?url=${encodeURIComponent(s.graphic)}`).then(x=>{s.image=x.image_url;s.imageFallback=x.fallback_image_url}).catch(()=>{}));if(s.discussionUrl)jobs.push(api(`/api/storms/nhc-advisory?url=${encodeURIComponent(s.discussionUrl)}`).then(x=>s.discussion=officialDiscussion(x.text)).catch(()=>{}));await Promise.allSettled(jobs)}
function impacts(s){if(!s.forecast.length)return[];const hits=new Map();s.forecast.forEach(p=>state.airports.forEach(a=>{const d=nm(p,{lat:num(a.lat),lon:num(a.lon)}),r=(p.intensity||0)>=64?250:(p.intensity||0)>=34?180:120;if(d>r)return;const key=a.icao||a.iata,old=hits.get(key);if(!old||d<old.d)hits.set(key,{a,p,d})}));return[...hits.values()].map(x=>({...x,level:x.d<=75?'high':x.d<=150?'moderate':'low'})).sort((a,b)=>a.d-b.d).slice(0,8)}
function impactHtml(s){const rows=impacts(s);if(!s.forecast.length)return'<p class="impact-note">Awaiting official forecast positions; no airport-proximity screen is issued.</p>';if(!rows.length)return'<p class="impact-note">No inventory airport is within the official-track screening distance.</p>';return`<ul class="impact-list">${rows.map(x=>`<li><b class="impact-airport ${x.level}">${esc(x.a.iata||x.a.icao||'—')}</b><span>${Math.round(x.d)} nm · ${esc(utc(x.p.time))}</span></li>`).join('')}</ul>`}
function cards(){const n=$('stormCards');n.innerHTML=state.systems.length?state.systems.map(s=>{const badge=s.tcfa?'formation':(s.intensity||0)>=64?'high':(s.intensity||0)>=34?'moderate':'low';return`<article class="storm-card ${s.id===state.selectedId?'selected':''}" data-id="${esc(s.id)}" tabindex="0" role="button"><header><div><span class="section-label">${esc(s.source)}</span><h3>${esc(s.name)}</h3></div><strong class="storm-badge ${badge}">${s.tcfa?'TCFA':Number.isFinite(s.intensity)?`${Math.round(s.intensity)} KT`:'—'}</strong></header><p class="storm-position"><b>${esc(pos(s.position))}</b><span>${esc(basin(s))}</span></p><span class="impact-label">AIRPORT PROXIMITY SCREEN</span>${impactHtml(s)}<small>View official details →</small></article>`}).join(''):'<p class="storm-empty">No active systems returned.</p>';n.querySelectorAll('[data-id]').forEach(c=>{const open=()=>select(c.dataset.id);c.onclick=open;c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}})}
function detail(s){const n=$('stormDetail');if(!s){n.classList.add('hidden');return}const image=s.image||s.graphic?`<figure class="official-track"><img src="${esc(s.image||s.graphic)}" ${s.imageFallback?`onerror="this.onerror=null;this.src='${esc(s.imageFallback)}'"`:''} alt="Official agency track graphic for ${esc(s.name)}"><figcaption>Original agency-issued track graphic · <a href="${esc(s.graphic)}" target="_blank" rel="noopener noreferrer">View on official website ↗</a></figcaption></figure>`:`<div class="graphic-unavailable"><b>Official track graphic unavailable</b><span>${s.tcfa?'JTWC has issued a formation alert, not a forecast-track graphic.':'The agency has not published a current track graphic. Use the official agency link below.'}</span></div>`;const facts=`<div class="storm-facts"><div><span>Current position</span><b>${esc(pos(s.position))}</b></div><div><span>Basin</span><b>${esc(basin(s))}</b></div><div><span>Official issue / update</span><b>${esc(utc(s.issued))}</b></div><div><span>Maximum wind</span><b>${Number.isFinite(s.intensity)?`${Math.round(s.intensity)} kt`:'Not supplied'}</b></div><div><span>Central pressure</span><b>${Number.isFinite(s.pressure)?`${Math.round(s.pressure)} hPa`:'Not supplied'}</b></div><div><span>Movement</span><b>${esc(s.movement)}</b></div></div>`;const table=s.forecast.length?`<section class="detail-block"><h3>Forecast positions & intensity</h3><table class="storm-table"><thead><tr><th>Valid time (UTC)</th><th>Position</th><th>Maximum wind</th></tr></thead><tbody>${s.forecast.map(p=>`<tr><td>${esc(utc(p.time))}</td><td>${esc(pos(p))}</td><td>${Number.isFinite(p.intensity)?`${Math.round(p.intensity)} kt`:'—'}</td></tr>`).join('')}</tbody></table></section>`:'';const text=s.tcfa||s.discussion?`<section class="detail-block official-text"><h3>${s.tcfa?'Official JTWC formation alert':s.textTitle||'Official agency discussion'}</h3><pre>${esc(s.tcfa||s.discussion)}</pre></section>`:'';n.innerHTML=`<div class="section-heading"><div><span class="section-label">SELECTED OFFICIAL SYSTEM</span><h2>${esc(s.name)} <small>${esc(s.source)}</small></h2></div></div>${image}<div class="storm-detail-grid"><section><h3>Official system data</h3><p>${esc(s.classification)}. Values are passed through from the named agency; Weather machine does not independently forecast storm track or intensity.</p>${facts}<div class="storm-links">${s.links.map(([l,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(l)} ↗</a>`).join('')}</div></section><section class="detail-block"><h3>Airports potentially affected — proximity screen</h3><p>Airport-name colour shows geographic proximity to an official forecast centre; it is not an agency watch, warning, or wind-radius forecast.</p>${impactHtml(s)}</section></div>${table}${text}`;n.classList.remove('hidden')}
function select(id){const s=state.systems.find(x=>x.id===id);if(!s)return;state.selectedId=id;cards();detail(s);$('stormDetail').scrollIntoView({behavior:'smooth',block:'start'})}
async function load(){
  const refresh=$('refreshStorms');
  refresh.disabled=true;
  $('stormNotice').classList.remove('error');
  $('stormNotice').textContent='Retrieving official NHC / CPHC and JTWC advisory feeds…';
  try {
    const [n,j,i,a,ports,t]=await Promise.allSettled([
      api('/api/storms/nhc'),api('/api/storms/jtwc-warnings'),api('/api/storms/imd'),
      api('/api/storms/nrl'),api('/api/storms/airports'),api('/api/storms/jtwc-tcfas')
    ]);
    const alerts=t.status==='fulfilled'?(t.value.alerts||[]):[];
    const codes=new Set(alerts.map(item=>String(item.invest||'').toUpperCase()));
    const systems=[];
    if(n.status==='fulfilled')systems.push(...nhc(n.value));
    if(j.status==='fulfilled')systems.push(...jtwc(j.value));
    if(i.status==='fulfilled')systems.push(...imdSystems(i.value));
    if(a.status==='fulfilled')systems.push(...nrl(a.value,codes));
    state.airports=ports.status==='fulfilled'?ports.value:[];
    systems.forEach(system=>{
      const alert=alerts.find(item=>String(item.invest||'').toUpperCase()===system.code);
      if(alert?.text){system.tcfa=alert.text;system.links.splice(1,0,['JTWC TCFA text',alert.url]);}
    });
    await Promise.allSettled(systems.filter(system=>system.source==='NHC / CPHC').map(enrich));
    state.systems=systems;
    state.selectedId=systems[0]?.id||null;
    $('stormCount').textContent=systems.length?`${systems.length} active system${systems.length===1?'':'s'}`:'No active systems returned';
    $('stormPositions').textContent=`${systems.reduce((count,system)=>count+system.forecast.length,0)} agency forecast points`;
    $('stormImpact').textContent=state.airports.length?'Local airport inventory ready':'Airport screening unavailable';
    cards();detail(systems[0]);
    const failures=[n,j,a].filter(result=>result.status==='rejected').length;
    $('stormNotice').textContent=failures?'Some official feeds are temporarily unavailable; displayed systems are from the feeds that responded.':'Official feeds loaded. Western Pacific warnings use JTWC; JTWC INVESTs are shown only while their official TCFA is active.';
  } catch(error) {
    state.systems=[];
    state.selectedId=null;
    cards();detail(null);
    $('stormCount').textContent='Feed unavailable';
    $('stormPositions').textContent='—';
    $('stormImpact').textContent='Unavailable';
    $('stormNotice').classList.add('error');
    $('stormNotice').textContent=`Unable to load official storm feeds: ${error.message||'unknown error'}`;
  } finally { refresh.disabled=false; }
}
function imdSystems(){return[]}
$('refreshStorms').onclick=load;load();
