const map = L.map('hazardMap', { worldCopyJump: true, minZoom: 2 }).setView([18, 20], 2);
// Use the same dependable, key-free basemap as the cyclone and ash maps.
// The previous provider started serving an "API key required" watermark.
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 8, attribution: '&copy; OpenStreetMap contributors' }).addTo(map);

const layerSelect = document.querySelector('#hazardLayer');
const timeSelect = document.querySelector('#hazardTime');
const levelSelect = document.querySelector('#hazardLevel');
const status = document.querySelector('#hazardStatus');
const mapTitle = document.querySelector('#mapTitle');
const mapMeta = document.querySelector('#mapMeta');
const guideTitle = document.querySelector('#guideTitle');
const guideText = document.querySelector('#guideText');
const key = document.querySelector('#hazardKey');
let manifest = null;
let displayed = L.layerGroup().addTo(map);

const layerGuide = {
  sigmet: { title: 'Official SIGMETs', text: 'Current international and domestic aviation warnings shown as issuing-agency polygons. Click a polygon for its bulletin information.', meta: 'Worldwide · official GeoJSON', key: [['#ff7f79', 'SIGMET polygon', 'Issuing-agency warning geometry']] },
  turbulence: { title: 'GFS turbulence potential', text: 'Broad potential estimated from GFS upper-wind speed, horizontal gradient and vertical wind shear. This is not an official turbulence forecast.', meta: 'GFS diagnostic · selected FL', key: [['#66d1ad', 'Low potential', 'Lower diagnostic score'], ['#f2c65c', 'Moderate potential', 'Elevated diagnostic score'], ['#ff7f79', 'High potential', 'Highest diagnostic score']] },
  icing: { title: 'GFS icing potential', text: 'Broad potential estimated from GFS temperature and relative humidity at the selected flight level. This is not an official icing forecast.', meta: 'GFS diagnostic · selected FL', key: [['#66d1ad', 'Low potential', 'Lower diagnostic score'], ['#f2c65c', 'Moderate potential', 'Elevated diagnostic score'], ['#ff7f79', 'High potential', 'Highest diagnostic score']] },
  wind: { title: 'GFS wind / temperature', text: 'Sampled GFS wind barbs and air temperature at the selected flight level. Arrow orientation is the reported wind direction.', meta: 'GFS model field · selected FL', key: [['#8cbbd5', 'Wind arrow', 'Direction and speed in knots'], ['#d7edf8', 'Temperature', 'Shown in each marker popup']] },
  convection: { title: 'GFS convection potential', text: 'Broad convection potential estimated from GFS CAPE and total cloud cover. Consult official convective warnings and products.', meta: 'GFS diagnostic · selected time', key: [['#66d1ad', 'Low potential', 'Lower diagnostic score'], ['#f2c65c', 'Moderate potential', 'Elevated diagnostic score'], ['#ff7f79', 'High potential', 'Highest diagnostic score']] }
};

function setStatus(message, isError = false) { status.textContent = message; status.classList.toggle('error', isError); }
function scoreColor(score) { return score >= 0.67 ? '#ff7f79' : score >= 0.35 ? '#f2c65c' : '#66d1ad'; }
function scoreLabel(score) { return score >= 0.67 ? 'High potential' : score >= 0.35 ? 'Moderate potential' : 'Low potential'; }
function kt(value) { return Number.isFinite(value) ? `${Math.round(value)} kt` : '—'; }
function celsius(value) { return Number.isFinite(value) ? `${Math.round(value)} °C` : '—'; }

function applyGuide() {
  const guide = layerGuide[layerSelect.value];
  mapTitle.textContent = guide.title;
  mapMeta.textContent = guide.meta;
  guideTitle.textContent = guide.title;
  guideText.textContent = guide.text;
  key.innerHTML = guide.key.map(([color, title, description]) => `<li><i style="background:${color}"></i><span><b>${title}</b>${description}</span></li>`).join('');
}

function clearDisplayed() { displayed.clearLayers(); }
function makePopup(properties, heading) {
  const values = Object.entries(properties || {}).filter(([name, value]) => value !== null && value !== undefined && value !== '' && !['style'].includes(name)).slice(0, 12);
  return `<div class="hazard-popup"><b>${heading}</b>${values.map(([name, value]) => `<span>${name.replace(/_/g, ' ')}: ${String(value)}</span>`).join('')}</div>`;
}

async function showSigmets() {
  clearDisplayed();
  setStatus('Loading official SIGMET polygons…');
  const response = await fetch('assets/gfs-hazards/sigmets.geojson', { cache: 'no-store' });
  if (!response.ok) throw new Error('Official SIGMET file has not yet been generated by the scheduled workflow.');
  const data = await response.json();
  const geojson = L.geoJSON(data, {
    style: { color: '#ff7f79', weight: 2, fillColor: '#d54e4a', fillOpacity: .25, className: 'sigmet-shape' },
    pointToLayer: (_, latlng) => L.circleMarker(latlng, { radius: 6, color: '#ff7f79', fillColor: '#d54e4a', fillOpacity: .8 }),
    onEachFeature: (feature, layer) => layer.bindPopup(makePopup(feature.properties, 'Official SIGMET'))
  });
  displayed.addLayer(geojson);
  const count = Array.isArray(data.features) ? data.features.length : 0;
  setStatus(`${count} official SIGMET feature${count === 1 ? '' : 's'} loaded.`);
  if (geojson.getBounds().isValid()) map.fitBounds(geojson.getBounds(), { padding: [20, 20], maxZoom: 4 });
}

async function showGfsLayer() {
  clearDisplayed();
  const layer = layerSelect.value;
  const valid = timeSelect.value;
  const level = levelSelect.value;
  if (!valid || !level) throw new Error('Generated GFS layers are not available yet.');
  setStatus(`Loading GFS ${layer} layer…`);
  const response = await fetch(`assets/gfs-hazards/layers/${valid}/${level}.geojson`, { cache: 'no-store' });
  if (!response.ok) throw new Error('Selected GFS layer has not yet been generated by the scheduled workflow.');
  const data = await response.json();
  const features = data.features || [];
  features.forEach((feature) => {
    const [longitude, latitude] = feature.geometry.coordinates;
    const point = feature.properties || {};
    let marker;
    if (layer === 'wind') {
      const arrow = Number.isFinite(point.wind_from_deg) ? '↓' : '•';
      marker = L.marker([latitude, longitude], { icon: L.divIcon({ className: 'wind-arrow', html: `<span style="display:block;transform:rotate(${Number(point.wind_from_deg || 0) + 180}deg)">${arrow}</span>`, iconSize: [18, 18], iconAnchor: [9, 9] }) });
      marker.bindPopup(makePopup({ wind: kt(point.wind_kt), direction: Number.isFinite(point.wind_from_deg) ? `${Math.round(point.wind_from_deg)}°` : '—', temperature: celsius(point.temperature_c), relative_humidity: Number.isFinite(point.relative_humidity) ? `${Math.round(point.relative_humidity)}%` : '—', valid: data.properties?.valid_time, flight_level: `FL${data.properties?.flight_level}` }, 'GFS wind / temperature'));
    } else {
      const score = Number(point[`${layer}_score`]);
      // Each downloaded value represents a roughly 4° × 4° sampled GFS cell.
      // Render a softly blended cell, rather than a dot, so the layer reads as
      // a continuous area of potential and not a collection of observations.
      const color = scoreColor(score);
      const opacity = score >= .67 ? .56 : score >= .35 ? .39 : .18;
      marker = L.rectangle([[latitude - 2, longitude - 2], [latitude + 2, longitude + 2]], {
        color,
        weight: score >= .67 ? 1 : .35,
        opacity: score >= .67 ? .82 : .42,
        fillColor: color,
        fillOpacity: opacity,
        interactive: true,
      });
      marker.bindPopup(makePopup({ potential: scoreLabel(score), score: Number.isFinite(score) ? score.toFixed(2) : '—', wind: kt(point.wind_kt), temperature: celsius(point.temperature_c), relative_humidity: Number.isFinite(point.relative_humidity) ? `${Math.round(point.relative_humidity)}%` : '—', valid: data.properties?.valid_time, flight_level: `FL${data.properties?.flight_level}` }, `GFS ${layer} potential`));
    }
    displayed.addLayer(marker);
  });
  setStatus(`GFS ${layer} diagnostic loaded: ${features.length} gridded diagnostic cells.`);
}

async function drawMap() {
  applyGuide();
  try { if (layerSelect.value === 'sigmet') await showSigmets(); else await showGfsLayer(); }
  catch (error) { clearDisplayed(); setStatus(error.message || 'Hazard layer could not be loaded.', true); }
}

async function loadManifest() {
  try {
    const response = await fetch('assets/gfs-hazards/manifest.json', { cache: 'no-store' });
    if (!response.ok) throw new Error('The scheduled GFS map build has not run yet.');
    manifest = await response.json();
    const times = manifest.valid_times || [];
    const levels = manifest.flight_levels || [];
    timeSelect.innerHTML = times.map((time) => `<option value="${time.path}">${time.label}</option>`).join('');
    levelSelect.innerHTML = levels.map((level) => `<option value="${level}">FL${level}</option>`).join('');
    timeSelect.disabled = !times.length;
    levelSelect.disabled = !levels.length;
    if (!times.length || !levels.length) throw new Error('The generated manifest contains no GFS layers.');
    setStatus(`GFS run ${manifest.run_label || 'available'} · generated ${manifest.generated_at || 'recently'}.`);
  } catch (error) {
    timeSelect.innerHTML = '<option>Not generated yet</option>'; levelSelect.innerHTML = '<option>Not generated yet</option>';
    timeSelect.disabled = true; levelSelect.disabled = true;
    setStatus(`${error.message} Official SIGMETs can still load once generated.`, true);
  }
  drawMap();
}

layerSelect.addEventListener('change', drawMap);
timeSelect.addEventListener('change', drawMap);
levelSelect.addEventListener('change', drawMap);
document.querySelector('#hazardRefresh').addEventListener('click', loadManifest);
applyGuide();
loadManifest();
